name: sync2cnb.yaml
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Sync to CNB Repository"
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL=${{ secrets.GIT_REPO }} \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME=${{ secrets.GIT_USERNAME }} \
            -e PLUGIN_PASSWORD=${{ secrets.GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync